// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFAQBd3Qd4jTV1sQ3bZPrI-f5N0U1nPUo',
    appId: '1:1010312886190:web:c55aab475bf78999b0ba3f',
    messagingSenderId: '1010312886190',
    projectId: 'faith-connect-fa188',
    authDomain: 'faith-connect-fa188.firebaseapp.com',
    storageBucket: 'faith-connect-fa188.firebasestorage.app',
    measurementId: 'G-Y76Y4XR66B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuIZT_Vt4uYRdDqaD1OpGvsnS2DGyvweg',
    appId: '1:1010312886190:android:095a9608670bd86fb0ba3f',
    messagingSenderId: '1010312886190',
    projectId: 'faith-connect-fa188',
    storageBucket: 'faith-connect-fa188.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxrUvr2Uif41cqqSRvfZItR0qb5TZzBS0',
    appId: '1:1010312886190:ios:1fdb82dbf4a6e506b0ba3f',
    messagingSenderId: '1010312886190',
    projectId: 'faith-connect-fa188',
    storageBucket: 'faith-connect-fa188.firebasestorage.app',
    iosBundleId: 'com.mh.faithconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxrUvr2Uif41cqqSRvfZItR0qb5TZzBS0',
    appId: '1:1010312886190:ios:1fdb82dbf4a6e506b0ba3f',
    messagingSenderId: '1010312886190',
    projectId: 'faith-connect-fa188',
    storageBucket: 'faith-connect-fa188.firebasestorage.app',
    iosBundleId: 'com.mh.faithconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFAQBd3Qd4jTV1sQ3bZPrI-f5N0U1nPUo',
    appId: '1:1010312886190:web:02f66527938674d9b0ba3f',
    messagingSenderId: '1010312886190',
    projectId: 'faith-connect-fa188',
    authDomain: 'faith-connect-fa188.firebaseapp.com',
    storageBucket: 'faith-connect-fa188.firebasestorage.app',
    measurementId: 'G-JSXJRPHHXD',
  );
}
